INSERT INTO ACCOUNTS VALUES(1);
INSERT INTO ACCOUNTS VALUES(2);
INSERT INTO ACCOUNTS VALUES(3);
INSERT INTO ITEMS VALUES(1, 'TEST1', 'test desc1');
INSERT INTO ITEMS VALUES(2, 'TEST2', 'test desc2');
INSERT INTO ITEMS VALUES(3, 'TEST3', 'test desc3');
